import os
import pandas as pd
import streamlit as st

st.set_page_config(page_title="House Price Regression", page_icon="🏠", layout="wide")

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "data", "train.csv")
OUT = os.path.join(ROOT, "outputs")

st.title("🏠 House Price Regression Analysis")
st.caption("125M1H026 | Formative Assessment 01 | Log Transformation + StandardScaler")

if not os.path.exists(DATA):
    st.error("data/train.csv was not found.")
    st.stop()

df = pd.read_csv(DATA)

st.sidebar.header("Project Sections")
section = st.sidebar.radio("Go to", [
    "Overview", "Raw Data", "Outliers", "Transformation",
    "Model Comparison", "Predictions"
])

if section == "Overview":
    st.header("🎯 Project Overview")
    a,b,c = st.columns(3)
    a.metric("Rows", f"{len(df):,}")
    b.metric("Columns", f"{df.shape[1]:,}")
    c.metric("Target", "SalePrice")
    st.write("This dashboard displays the main outputs generated by the analysis notebook.")
    st.subheader("Pipeline")
    st.code("Explore → Outliers → Baseline → Log Transform → Scaling → Regression → Compare")

elif section == "Raw Data":
    st.header("📊 Raw Data")
    st.dataframe(df.head(20), use_container_width=True)
    st.subheader("Summary Statistics")
    st.dataframe(df.describe().T, use_container_width=True)

elif section == "Outliers":
    st.header("📦 Outlier Analysis")
    before = os.path.join(OUT, "boxplots_before_outlier_handling.png")
    after = os.path.join(OUT, "boxplots_after_outlier_handling.png")
    if os.path.exists(before):
        st.subheader("Before Treatment")
        st.image(before, use_container_width=True)
    if os.path.exists(after):
        st.subheader("After Selected IQR Capping")
        st.image(after, use_container_width=True)

elif section == "Transformation":
    st.header("🔄 Log Transformation")
    image = os.path.join(OUT, "before_and_after_log.png")
    if os.path.exists(image):
        st.image(image, use_container_width=True)
    else:
        st.warning("Run the notebook first to generate the transformation output.")

elif section == "Model Comparison":
    st.header("⚖️ Model Comparison")
    results = os.path.join(OUT, "model_comparison.csv")
    if os.path.exists(results):
        table = pd.read_csv(results)
        st.dataframe(table, use_container_width=True)
        chart = os.path.join(OUT, "model_comparison.png")
        if os.path.exists(chart):
            st.image(chart, use_container_width=True)
    else:
        st.warning("Run the notebook first to generate model_comparison.csv.")

elif section == "Predictions":
    st.header("🎯 Prediction Results")
    for title, filename in [
        ("Before Transformation", "baseline_actual_vs_predicted.png"),
        ("After Log + Scaling", "transformed_actual_vs_predicted.png"),
        ("Regression Line", "regression_line.png")
    ]:
        image = os.path.join(OUT, filename)
        if os.path.exists(image):
            st.subheader(title)
            st.image(image, use_container_width=True)
        else:
            st.warning(f"{filename} has not been generated yet.")

st.divider()
st.caption("Run the notebook before opening the final dashboard.")
